package com.stmanagement.service;

import com.stmanagement.dto.BankAccountDTO;
import com.stmanagement.dto.CustomerDTO;
import com.stmanagement.model.Customer;
import com.stmanagement.repository.BankAccountRepository;
import com.stmanagement.repository.CustomerRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Sort;
import org.springframework.data.jpa.domain.Specification;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.util.StringUtils;

import javax.persistence.EntityManager;
import javax.persistence.criteria.Predicate;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

@Service
@RequiredArgsConstructor
public class CustomerService {

    private final CustomerRepository customerRepository;
    private final BankAccountRepository bankAccountRepository;
    private final EntityManager entityManager;

    public Page<CustomerDTO> findAll(String keyword, int page, int size) {
        Specification<Customer> spec = (root, query, cb) -> {
            List<Predicate> predicates = new ArrayList<>();
            if (StringUtils.hasText(keyword)) {
                String pattern = "%" + keyword + "%";
                predicates.add(cb.or(
                        cb.like(cb.lower(root.get("customerCode")), pattern),
                        cb.like(cb.lower(root.get("companyName")), pattern)
                ));
            }
            return cb.and(predicates.toArray(new Predicate[0]));
        };
        PageRequest pageable = PageRequest.of(page, size, Sort.by("customerCode").ascending());
        return customerRepository.findAll(spec, pageable).map(entity -> {
            CustomerDTO dto = toDTO(entity);
            List<String> labels = bankAccountRepository.findByCustomerId(entity.getId())
                    .stream().map(ba -> ba.getBankName() + "（" + ba.getBranchCode() + "）")
                    .collect(Collectors.toList());
            dto.setTorihikiNo(labels.isEmpty() ? null : String.join("、", labels));
            return dto;
        });
    }

    public CustomerDTO findById(Long id) {
        Customer entity = customerRepository.findById(id)
                .orElseThrow(() -> new RuntimeException("顧客が見つかりません: " + id));
        CustomerDTO dto = toDTO(entity);
        // Attach linked bank accounts
        dto.setBankAccounts(bankAccountRepository.findByCustomerId(id)
                .stream().map(this::toBankAccountDTO).collect(Collectors.toList()));
        return dto;
    }

    @Transactional
    public CustomerDTO create(CustomerDTO dto) {
        Customer entity = toEntity(dto);
        // customerCode is auto-generated by DB (insertable=false)
        entity.setCustomerCode(null);
        entity = customerRepository.save(entity);
        entityManager.flush();
        entityManager.refresh(entity);
        return toDTO(entity);
    }

    @Transactional
    public CustomerDTO update(Long id, CustomerDTO dto) {
        Customer entity = customerRepository.findById(id)
                .orElseThrow(() -> new RuntimeException("顧客が見つかりません: " + id));

        // customerCode is auto-generated, not updatable — skip
        entity.setCompanyName(dto.getCompanyName());
        entity.setPresidentName(dto.getPresidentName());
        entity.setWebsite(dto.getWebsite());
        entity.setAddress(dto.getAddress());
        entity.setContactName(dto.getContactName());
        entity.setEmail(dto.getEmail());
        entity.setPhone(dto.getPhone());
        entity.setSalesRepName(dto.getSalesRepName());
        entity.setSalesRepPhone(dto.getSalesRepPhone());
        entity.setSalesRepEmail(dto.getSalesRepEmail());
        entity.setAdminRepName(dto.getAdminRepName());
        entity.setAdminRepPhone(dto.getAdminRepPhone());
        entity.setAdminRepEmail(dto.getAdminRepEmail());
        entity.setTorihikiNo(dto.getTorihikiNo());
        entity = customerRepository.save(entity);
        return toDTO(entity);
    }

    @Transactional
    public void delete(Long id) {
        if (!customerRepository.existsById(id)) {
            throw new RuntimeException("顧客が見つかりません: " + id);
        }
        customerRepository.deleteById(id);
    }

    private CustomerDTO toDTO(Customer entity) {
        return CustomerDTO.builder()
                .id(entity.getId())
                .customerCode(entity.getCustomerCode())
                .companyName(entity.getCompanyName())
                .presidentName(entity.getPresidentName())
                .website(entity.getWebsite())
                .address(entity.getAddress())
                .contactName(entity.getContactName())
                .email(entity.getEmail())
                .phone(entity.getPhone())
                .salesRepName(entity.getSalesRepName())
                .salesRepPhone(entity.getSalesRepPhone())
                .salesRepEmail(entity.getSalesRepEmail())
                .adminRepName(entity.getAdminRepName())
                .adminRepPhone(entity.getAdminRepPhone())
                .adminRepEmail(entity.getAdminRepEmail())
                .torihikiNo(entity.getTorihikiNo())
                .build();
    }

    private Customer toEntity(CustomerDTO dto) {
        return Customer.builder()
                .customerCode(dto.getCustomerCode())
                .companyName(dto.getCompanyName())
                .presidentName(dto.getPresidentName())
                .website(dto.getWebsite())
                .address(dto.getAddress())
                .contactName(dto.getContactName())
                .email(dto.getEmail())
                .phone(dto.getPhone())
                .salesRepName(dto.getSalesRepName())
                .salesRepPhone(dto.getSalesRepPhone())
                .salesRepEmail(dto.getSalesRepEmail())
                .adminRepName(dto.getAdminRepName())
                .adminRepPhone(dto.getAdminRepPhone())
                .adminRepEmail(dto.getAdminRepEmail())
                .torihikiNo(dto.getTorihikiNo())
                .build();
    }

    private BankAccountDTO toBankAccountDTO(com.stmanagement.model.BankAccount entity) {
        return BankAccountDTO.builder()
                .id(entity.getId())
                .torihikiNo(entity.getTorihikiNo())
                .customerId(entity.getCustomerId())
                .branchCode(entity.getBranchCode())
                .bankName(entity.getBankName())
                .accountType(entity.getAccountType())
                .accountNumber(entity.getAccountNumber())
                .accountHolder(entity.getAccountHolder())
                .build();
    }
}
